### ISSUE TITLE
Nerves usage

### ISSUE THREAD

**Issue by hopsor** [Kraigie/mixcord#393]
Hi,

I've been trying to integrate nostrum inside a Nerves project. However I haven't had any success. Has anyone been able to do it?

When I added the dependency normally it crashed due to this:

> 17:45:10.194 [info]  Application nostrum exited: Nostrum.Application.start(:normal, []) returned an error: shutdown: failed to start child: Nostrum.Shard.Supervisor
    ** (EXIT) an exception was raised:
        ** (CaseClauseError) no case clause matching: {:error, %HTTPoison.Error{id: nil, reason: :nxdomain}}
            (nostrum 0.4.6) lib/nostrum/util.ex:145: Nostrum.Util.get_new_gateway_url/0
            (nostrum 0.4.6) lib/nostrum/shard/supervisor.ex:16: Nostrum.Shard.Supervisor.start_link/1
            (stdlib 3.17) supervisor.erl:414: :supervisor.do_start_child_i/3
            (stdlib 3.17) supervisor.erl:400: :supervisor.do_start_child/2
            (stdlib 3.17) supervisor.erl:384: anonymous fn/3 in :supervisor.start_children/2
            (stdlib 3.17) supervisor.erl:1250: :supervisor.children_map/4
            (stdlib 3.17) supervisor.erl:350: :supervisor.init_children/2
            (stdlib 3.17) gen_server.erl:423: :gen_server.init_it/2

I imagine this is happening because the internet connection is not up before the RateLimiter tries to connect.

I tried instead by adding the dependency using `runtime: false`. However, when I try to start the app manually after the internet connection is up doing `Application.start(:nostrum)` I get this error: `{:error, {‘no such file or directory’, ‘nostrum.app’}}`

Anyone can help with this?

**Comment by hopsor** [comment]
Hi @jchristgit 

Thanks for the quick response. Once the network interface is connected to internet there is no issues looking up `discord.com`. 

```
nil
iex(7)> :inet_res.lookup('discord.com', :in, :a)
[
  {162, 159, 137, 232},
  {162, 159, 135, 232},
  {162, 159, 128, 233},
  {162, 159, 136, 232},
  {162, 159, 138, 232}
]
```

To give you more context, I'm running my project in a Raspberry Pi Zero 2 W using wifi connectivity.

After spending some time digging into this I realised nostrum connects to discord.com via `RateLimiter` as soon as the app boots, which is before the wlan0 network interface is ready and then it crashes. I'm pretty new to nerves and nostrum so I'm not sure how valid is my opinion. However I believe it'll be easily solved by having the option to decide when to connect to discord.com instead of being forced as soon as the nostrum app starts. I think the design choice of connecting to discord.com in the boot is more suitable for web projects than for embedded devices.

**Comment by jchristgit** [comment]
Thanks for the `:inet_res` debug.

> After spending some time digging into this I realised nostrum connects to discord.com via RateLimiter as soon as the app boots, which is before the wlan0 network interface is ready and then it crashes. I'm pretty new to nerves and nostrum so I'm not sure how valid is my opinion. However I believe it'll be easily solved by having the option to decide when to connect to discord.com instead of being forced as soon as the nostrum app starts. I think the design choice of connecting to discord.com in the boot is more suitable for web projects than for embedded devices.

So I think in the happy OTP case, nostrum shouldn't be started before the backing device is started. Do you have any logs that show when the interface becomes ready?

As for connecting when it starts, one thing we _could_ do (which would also be reasonable for regular startup) would be moving the connection open into a `continue` callback. I don't think that that would fix the backing issue though.

Also, you mention the ratelimiter in your second comment, but the traceback in the original post refers to the shard supervisor asking for the bot gateway endpoint. I'm not really sure if we can adjust that part, since the shard sessions need the endpoint to connect to, so blocking there is (mostly) fine..

**Comment by hopsor** [comment]
Here are my logs: https://pastebin.com/B4NhtavT

You can see the Shard supervisor starts way before the wifi adapter finishes

**Comment by jchristgit** [comment]
The logs have disappeared unfortunately 🙁 

Is it possible to stop Elixir from automatically starting nostrum via the `runtime: false` option in `mix.exs`, and then starting it manually?

**Comment by hopsor** [comment]
I don't understand why the logs aren't there anymore. I believe I didn't set any expiration time. Sorry :-(

Regarding your question. I tried using `runtime: false` already. However when I try to manually start the app using `Application.start(:nostrum)` I get this error `{:error, {'no such file or directory', 'nostrum.app'}}`

**Comment by jchristgit** [comment]
Sorry, I somehow forgot that that was already part of the original issue 🤦 

The `Application.start` error is strange. .. this works as expected for me locally (using `ensure_all_started` to also start dependencies):

```elixir
Interactive Elixir (1.13.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Application.start(:nostrum)
{:error, {:not_started, :gun}}
iex(2)> Application.ensure_started(:nostrum)
{:error, {:not_started, :gun}}
iex(3)> Application.ensure_all_started(:nostrum)
{:ok,
 [:cowlib, :gun, :certifi, :ed25519, :curve25519, :salsa20, :chacha20,
  :equivalex, :poly1305, :kcl, :porcelain, :mime, :gen_stage, :nostrum]}
iex(4)> 
23:12:53.709 [debug] Websocket connection up on worker #PID<0.422.0>
 
23:12:53.721 [info]  IDENTIFYING
 
23:12:53.870 [debug] HEARTBEAT_ACK
 
```

I _kind of_ have a feeling that the error is due to the way nerves deploys your software onto the target system. Is there maybe some other app we can test this with, can you maybe try it with `mnesia`?
```elixir
iex(9)> Application.ensure_all_started(:mnesia)
{:ok, [:mnesia]}
```

**Comment by ConnorRigby** [comment]
Hey all, not sure if this was ever resolved, but i could walk someone thru the workaround for making this work if more details are needed. This isn't a *good* way to do it. In my opinion Nostrum shouldn't be an application at all, but that's probably out of  the scope of this particular issue. 

Here's the gist of the workaround you can use
1) create a handler for [shoehorn](https://github.com/nerves-project/shoehorn#handling-application-failures)
2) inside that handler, catch the first nostrum exit (there's nothing you can do about it crashing, it'll never work without internet)
3) don't restart it immediately. You'll need some other trigger to restart it. One simple  way  to do this is to use [vintage_net](https://github.com/nerves-networking/vintage_net) for this. I set `internet_host_list` to include the discord api hostname. You can subscribe to notifications about being able to resolve that address. 
4) when the server DNS resolution completes, restart nostrum
5) if internet connectivity is lost, return to 2

Hopefully that helps. If anyone gets stuck here, let me know i can probably help.

**Comment by jchristgit** [comment]
Hello all, did one of you have time to check this fix out? I was wondering if I should add it to the documentation, would be useful to know if it works as I don't have a nerves device. 🙂
